name: aws_uploader
description: A Flutter plugin to upload any file to AWS S3 using Cognito Developer Identity (token + identityId). Supports real-time progress streaming, upload cancellation, and multi-part uploads on Android and iOS.
version: 0.1.0
homepage: https://github.com/brijeshuniqual/aws_uploader
repository: https://github.com/brijeshuniqual/aws_uploader
issue_tracker: https://github.com/brijeshuniqual/aws_uploader/issues

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.uqbrijesh.aws.uploader
        pluginClass: AwsUploaderPlugin
      ios:
        pluginClass: AwsUploaderPlugin
